name: hatofit
description: "A mobile application for fitness tracking and workout planning."
publish_to: "none"
version: 1.0.1+7

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: 3.16.8

dependencies:
  better_player: ^0.0.84
  cached_network_image: ^3.3.1
  circular_countdown_timer: ^0.2.4
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  firebase_analytics: ^10.8.4
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.31.13
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  functional_data: ^1.1.1
  get_it: ^7.6.7
  go_router: ^14.2.2
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  # internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  keep_screen_on: ^3.0.0
  liquid_swipe: ^3.1.0
  logger: ^2.4.0
  oktoast: ^3.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  pinput: ^3.0.1
  polar: ^7.0.0
  pretty_dio_logger: ^1.3.1
  syncfusion_flutter_charts: ^24.1.47+2
  syncfusion_flutter_gauges: ^24.2.3
  vibration: ^1.8.4
  video_player: ^2.9.1
  youtube_explode_dart: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  functional_data_generator: ^2.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/hatofit.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/images/avatar/
    - assets/images/icons/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
